// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/anonymous": {
            "post": {
                "description": "Creates an anonymous user and returns a JWT for API access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create anonymous user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.anonymousAuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/session": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verifies the bearer token and returns the authenticated user id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.authSessionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/match/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds the current user to the video matchmaking queue. Returns 202 while waiting or 200 when matched.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Join matchmaking queue",
                "parameters": [
                    {
                        "description": "Match preferences",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.joinMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.matchedResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/server.waitingMatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/match/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks the current user as having left matchmaking.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Leave matchmaking queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.leaveMatchResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/match/snapshot": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Saves a camera snapshot on the server after a match is created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Save match snapshot",
                "parameters": [
                    {
                        "description": "Snapshot payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.snapshotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.snapshotResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current user's anonymous social profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.profileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates display name, bio, interests, and age confirmation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update current user profile",
                "parameters": [
                    {
                        "description": "Profile fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.updateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.profileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/push/subscription": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Saves the current user's browser Web Push subscription so the server can notify them while offline.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "push"
                ],
                "summary": "Save browser push subscription",
                "parameters": [
                    {
                        "description": "Push subscription",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.pushSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.pushSubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/push/test": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a server-side Web Push notification to the current user's latest subscription.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "push"
                ],
                "summary": "Send a test push notification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.pushTestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "Returns current online users, waiting users, and users in active chats.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Runtime usage stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.statsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/block": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Blocks another user and prevents future matches.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "safety"
                ],
                "summary": "Block a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reason",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/server.userActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.userActionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/report": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reports another user for moderation review.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "safety"
                ],
                "summary": "Report a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reason",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/server.userActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.userActionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ws": {
            "get": {
                "description": "Upgrades to a WebSocket used for match and WebRTC signaling messages. Pass the JWT as the token query parameter.",
                "tags": [
                    "signaling"
                ],
                "summary": "Connect signaling WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the backend service health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.healthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.MatchMode": {
            "type": "string",
            "enum": [
                "video",
                "voice"
            ],
            "x-enum-varnames": [
                "MatchModeVideo",
                "MatchModeVoice"
            ]
        },
        "model.User": {
            "type": "object",
            "properties": {
                "ageConfirmed": {
                    "type": "boolean"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "firebaseUid": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.UserProfile": {
            "type": "object",
            "properties": {
                "ageConfirmed": {
                    "type": "boolean"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.anonymousAuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "server.authSessionResponse": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string",
                    "example": "4f6d8c2a7b1e4a9f8c0d2e3f5a6b7c8d"
                }
            }
        },
        "server.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "unauthorized"
                }
            }
        },
        "server.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "server.joinMatchRequest": {
            "type": "object",
            "properties": {
                "mode": {
                    "enum": [
                        "video"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.MatchMode"
                        }
                    ],
                    "example": "video"
                },
                "region": {
                    "type": "string",
                    "example": "global"
                }
            }
        },
        "server.leaveMatchResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "left"
                }
            }
        },
        "server.matchedResponse": {
            "type": "object",
            "properties": {
                "initiator": {
                    "type": "boolean",
                    "example": true
                },
                "peerId": {
                    "type": "string",
                    "example": "5f6d8c2a7b1e4a9f8c0d2e3f5a6b7c8d"
                },
                "peerProfile": {
                    "$ref": "#/definitions/model.UserProfile"
                },
                "roomId": {
                    "type": "string",
                    "example": "f9b9fdc7110a4a5cb6924f2d936cd58a"
                },
                "status": {
                    "type": "string",
                    "example": "matched"
                }
            }
        },
        "server.profileResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/model.UserProfile"
                }
            }
        },
        "server.pushSubscriptionKeys": {
            "type": "object",
            "properties": {
                "auth": {
                    "type": "string",
                    "example": "B8r..."
                },
                "p256dh": {
                    "type": "string",
                    "example": "BDp..."
                }
            }
        },
        "server.pushSubscriptionRequest": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "type": "string",
                    "example": "https://fcm.googleapis.com/fcm/send/..."
                },
                "keys": {
                    "$ref": "#/definitions/server.pushSubscriptionKeys"
                }
            }
        },
        "server.pushSubscriptionResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "saved"
                }
            }
        },
        "server.pushTestResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "sent"
                }
            }
        },
        "server.snapshotRequest": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 480
                },
                "image": {
                    "type": "string",
                    "example": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQ..."
                },
                "mode": {
                    "type": "string",
                    "example": "video"
                },
                "peerId": {
                    "type": "string",
                    "example": "5f6d8c2a7b1e4a9f8c0d2e3f5a6b7c8d"
                },
                "roomId": {
                    "type": "string",
                    "example": "f9b9fdc7110a4a5cb6924f2d936cd58a"
                },
                "width": {
                    "type": "integer",
                    "example": 640
                }
            }
        },
        "server.snapshotResponse": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "example": "/app/snapshots/2026-05-22/room-user.jpg"
                },
                "status": {
                    "type": "string",
                    "example": "saved"
                }
            }
        },
        "server.statsResponse": {
            "type": "object",
            "properties": {
                "chatting": {
                    "type": "integer",
                    "example": 8
                },
                "online": {
                    "type": "integer",
                    "example": 12
                },
                "waiting": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "server.updateProfileRequest": {
            "type": "object",
            "properties": {
                "ageConfirmed": {
                    "type": "boolean",
                    "example": true
                },
                "bio": {
                    "type": "string",
                    "example": "喜欢深夜聊天、电影和旅行"
                },
                "displayName": {
                    "type": "string",
                    "example": "Star Voyager"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "movie",
                        "music",
                        "travel"
                    ]
                }
            }
        },
        "server.userActionRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "inappropriate behavior"
                }
            }
        },
        "server.userActionResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "server.waitingMatchResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "waiting"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer \" followed by a JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Random Match API",
	Description:      "Backend API for anonymous random voice/video matching and WebSocket signaling.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
